lakehouse_medallion_demo:
    target: dev
    outputs:
      dev:
        catalog: null
        host: <<your_databricks_host>>.azuredatabricks.net
        http_path: <<your_databricks_path>>
        schema: default
        threads: 1
        token: <<your_databricks_token>>
        type: databricks